version: 2

sources:
  - name: raw
    database: MODERN_DATA_STACK
    schema: RAW
    tables:
      - name: customers_raw
        description: "Raw customer master data loaded from CSV."
        columns:
          - name: customer_id
            tests: [not_null, unique]
      - name: products_raw
        description: "Raw product master data loaded from CSV."
        columns:
          - name: product_id
            tests: [not_null, unique]
      - name: sellers_raw
        description: "Raw seller dimension for marketplace orders."
        columns:
          - name: seller_id
            tests: [not_null, unique]
      - name: orders_raw
        description: "Raw order headers (one row per order)."
        columns:
          - name: order_id
            tests: [not_null, unique]
          - name: customer_id
            tests:
              - not_null
      - name: order_items_raw
        description: "Raw order line items (one row per order line)."
        columns:
          - name: order_item_id
            tests: [not_null, unique]
          - name: order_id
            tests: [not_null]
          - name: product_id
            tests: [not_null]
      - name: refunds_raw
        description: "Refund transactions tied to orders / order items."
        columns:
          - name: refund_id
            tests: [not_null, unique]
      - name: events_raw
        description: "Raw product analytics events (page views, add_to_cart, etc.)."
        columns:
          - name: event_id
            tests: [not_null, unique]
