name: 'modern_data_stack_snowflake'
version: '1.0.0'
config-version: 2

profile: 'modern_data_stack_snowflake'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  modern_data_stack_snowflake:
    +materialized: view
    staging:
      +schema: transform
      +materialized: view
    intermediate:
      +schema: transform
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table
    metrics:
      +schema: analytics
      +materialized: view

vars:
  start_date: '2025-01-01'
  end_date: '2025-12-31'
