modern_data_stack_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'WH_ANALYTICS') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'MODERN_DATA_STACK') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'TRANSFORM') }}"
      threads: 4
      client_session_keep_alive: false
      query_tag: "dbt_modern_data_stack_project"
