-- Snowflake setup (runnable in Snowflake worksheet)

CREATE OR REPLACE WAREHOUSE ANALYTICS_WH;
CREATE OR REPLACE DATABASE ANALYTICS_DB;
CREATE OR REPLACE SCHEMA ANALYTICS_DB.RAW;

CREATE OR REPLACE ROLE ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_ROLE;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS_DB.RAW TO ROLE ANALYTICS_ROLE;

-- Example external stage (S3-backed)
-- CREATE OR REPLACE STAGE raw_stage
--   URL='s3://my-bucket/data/'
--   STORAGE_INTEGRATION=my_integration;