version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: created_date
        tests: [not_null]
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: amount_usd
        tests:
          - not_null
  - name: dim_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
  - name: fct_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: status
        tests:
          - accepted_values:
              values: ['paid']
  - name: mart_daily_revenue
    columns:
      - name: revenue_usd
        tests:
          - not_null
