version: 2

models:
  - name: fct_order_revenue
    columns:
      - name: order_id
        tests:
          - not_null
  - name: dim_customer_scd2
    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null
