version: 2

models:
  - name: dim_date
    description: "Calendar dimension for reporting."
    columns:
      - name: date_day
        tests: [not_null, unique]

  - name: dim_customer
    description: "Customer dimension used for segmentation and cohorting."
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_product
    description: "Product dimension including category/brand and cost inputs."
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: dim_seller
    description: "Marketplace seller dimension."
    columns:
      - name: seller_id
        tests: [not_null, unique]

  - name: fct_orders
    description: "Order-level fact table with gross and net revenue, refunds, and customer attributes."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: net_revenue
        tests:
          - dbt_utils.expression_is_true:
              expression: "net_revenue <= gross_revenue"

  - name: fct_order_items
    description: "Order item fact table with line revenue, cost, and gross profit."
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('fct_orders')
              field: order_id
      - name: line_gross_profit
        tests:
          - not_null

  - name: fct_events_daily
    description: "Daily funnel rollup from raw events."
    columns:
      - name: event_date
        tests: [not_null]

  - name: vw_kpi_daily
    description: "Convenience view for daily KPI trend (revenue, orders, AOV)."
