-- SNOWFLAKE SETUP (run as a role with privileges to create DB/SCHEMA/WAREHOUSE)
-- This project uses a RAW layer and an ANALYTICS layer, and a dbt-managed TRANSFORM schema.

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYTICS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS MODERN_DATA_STACK;
CREATE SCHEMA IF NOT EXISTS MODERN_DATA_STACK.RAW;
CREATE SCHEMA IF NOT EXISTS MODERN_DATA_STACK.ANALYTICS;

-- Optional: a dedicated schema for dbt models (recommended)
CREATE SCHEMA IF NOT EXISTS MODERN_DATA_STACK.TRANSFORM;

-- File format for CSVs
CREATE OR REPLACE FILE FORMAT MODERN_DATA_STACK.RAW.CSV_FMT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

-- Stage for local upload (Snowsight UI) or internal staging
CREATE OR REPLACE STAGE MODERN_DATA_STACK.RAW.RAW_STAGE
  FILE_FORMAT = MODERN_DATA_STACK.RAW.CSV_FMT;

-- RAW TABLES (landed 1:1 with source files)
CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.CUSTOMERS_RAW (
  customer_id STRING,
  signup_date DATE,
  country_code STRING,
  region STRING,
  is_b2b NUMBER(1,0),
  plan_tier STRING
);

CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.PRODUCTS_RAW (
  product_id STRING,
  category STRING,
  brand STRING,
  list_price NUMBER(10,2),
  unit_cost NUMBER(10,2),
  is_subscription NUMBER(1,0),
  is_active NUMBER(1,0)
);

CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.SELLERS_RAW (
  seller_id STRING,
  seller_tier STRING,
  seller_country_code STRING
);

CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.ORDERS_RAW (
  order_id STRING,
  customer_id STRING,
  order_ts TIMESTAMP_NTZ,
  channel STRING,
  traffic_source STRING,
  campaign STRING,
  payment_method STRING,
  shipping_method STRING,
  order_status STRING,
  seller_id STRING
);

CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.ORDER_ITEMS_RAW (
  order_item_id STRING,
  order_id STRING,
  product_id STRING,
  quantity NUMBER(10,0),
  list_price NUMBER(10,2),
  discount_pct NUMBER(5,4),
  unit_price NUMBER(10,2)
);

CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.REFUNDS_RAW (
  refund_id STRING,
  order_id STRING,
  order_item_id STRING,
  refund_ts TIMESTAMP_NTZ,
  refund_amount NUMBER(10,2),
  refund_reason STRING
);

CREATE OR REPLACE TABLE MODERN_DATA_STACK.RAW.EVENTS_RAW (
  event_id STRING,
  customer_id STRING,
  session_id STRING,
  event_ts TIMESTAMP_NTZ,
  device STRING,
  channel STRING,
  traffic_source STRING,
  campaign STRING,
  event_type STRING,
  product_id STRING,
  order_id STRING
);

-- LOAD DATA
-- Upload the CSV files to the internal stage RAW_STAGE using Snowsight:
--   Data > Databases > MODERN_DATA_STACK > Schemas > RAW > Stages > RAW_STAGE > + Files
-- Then run the COPY commands below.

COPY INTO MODERN_DATA_STACK.RAW.CUSTOMERS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/customers.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MODERN_DATA_STACK.RAW.PRODUCTS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/products.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MODERN_DATA_STACK.RAW.SELLERS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/sellers.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MODERN_DATA_STACK.RAW.ORDERS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/orders.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MODERN_DATA_STACK.RAW.ORDER_ITEMS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/order_items.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MODERN_DATA_STACK.RAW.REFUNDS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/refunds.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MODERN_DATA_STACK.RAW.EVENTS_RAW
  FROM @MODERN_DATA_STACK.RAW.RAW_STAGE/events.csv
  FILE_FORMAT = (FORMAT_NAME = MODERN_DATA_STACK.RAW.CSV_FMT)
  ON_ERROR = 'ABORT_STATEMENT';

-- Quick sanity checks
SELECT COUNT(*) AS customers FROM MODERN_DATA_STACK.RAW.CUSTOMERS_RAW;
SELECT COUNT(*) AS products  FROM MODERN_DATA_STACK.RAW.PRODUCTS_RAW;
SELECT COUNT(*) AS orders    FROM MODERN_DATA_STACK.RAW.ORDERS_RAW;
SELECT COUNT(*) AS items     FROM MODERN_DATA_STACK.RAW.ORDER_ITEMS_RAW;
SELECT COUNT(*) AS events    FROM MODERN_DATA_STACK.RAW.EVENTS_RAW;
